version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  # web:
  #   image: gocommerce
  #   ports:
  #     - 8080:8080
